package com.greek.main.hibernate.model;
// Generated 5 jul. 2021 17:48:18 by Hibernate Tools 3.2.2.GA and Assent Architecture


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gvt.core.domain.types.Auditable;
import com.gvt.core.domain.types.Cleanable;
import com.gvt.core.domain.types.Fillable;
import com.gvt.core.domain.types.Identificable;
import com.gvt.core.domain.types.Seleccionable;
import com.gvt.core.domain.types.Versionable;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Organizacion generated by hbm2java
 */
@Entity
@EntityListeners({ AuditingEntityListener.class })
@Table(name="organizacion"
    ,schema="public"
)
public class Organizacion  implements Versionable,Seleccionable,Identificable,Fillable,Cleanable,Auditable,java.io.Serializable {


	private static final long serialVersionUID = 1L;
 	
 	private Long id;
 	
 	private long version;
 	
 	private TipoOrganizacion tipoOrganizacion;
 	
 	private OpcionSino opcionSinoByEsHabilitado;
 	
 	private Organizacion organizacion;
 	
 	private OpcionSino opcionSinoByEsPersonaContactoRequired;
 	
 	private CodigoPostal codigoPostal;
 	
 	private String rifOrganizacion;
 	
 	private String nitOrganizacion;
 	
 	private String razonOrganizacion;
 	
 	private String telefonoFijoOrganizacion;
 	
 	private String telefonoSecundarioOrganizacion;
 	
 	private String EMailOrganizacion;
 	
 	private String direccionOrganizacion;
 	
 	private String cabecera;
 	
 	private String url1;
 	
 	private String url1FileName;
 	
 	private Double url1FileSize;
 	
 	private String formatoCabecera;
 	
 	private String formatoPiePagina;
 	
 	private String formatoFirma;
 	
 	private Long nextNroPedido;
 	
 	private String numeroImpFiscal;
 	@CreatedBy
 	private String usuarioCreacion;
 	@CreatedDate
 	private LocalDateTime fechaCreacion;
 	@LastModifiedBy
 	private String usuarioModificacion;
 	@LastModifiedDate
 	private LocalDateTime fechaModificacion;
 	
 	private Integer maxOrganizacionesPorGrupo;
 	
 	private Integer maxSedesPorOrganizacion;
 	
 	private String tituloResponsable;
 	
 	private String nombreResponsable;
 	
 	private Set<PropiedadesSistema> propiedadesSistemas = new HashSet<PropiedadesSistema>(0);
 	
 	private Set<UsuarioOrganizacion> usuarioOrganizacionsForIdOrganizacion = new HashSet<UsuarioOrganizacion>(0);
 	
 	private Set<PersonaOrganizacion> personaOrganizacions = new HashSet<PersonaOrganizacion>(0);
 	
 	private Set<UsuarioOrganizacion> usuarioOrganizacionsForIdSede = new HashSet<UsuarioOrganizacion>(0);
 	
 	private Set<Organizacion> organizacions = new HashSet<Organizacion>(0);
 	
 	private Set<UsuarioOrganizacion> usuarioOrganizacionsForIdSedeDefault = new HashSet<UsuarioOrganizacion>(0);

    public Organizacion() {
    	// default constructor
    }

	
    public Organizacion(OpcionSino opcionSinoByEsHabilitado, String rifOrganizacion, String razonOrganizacion) {
        this.opcionSinoByEsHabilitado = opcionSinoByEsHabilitado;
        this.rifOrganizacion = rifOrganizacion;
        this.razonOrganizacion = razonOrganizacion;
    }
    public Organizacion(TipoOrganizacion tipoOrganizacion, OpcionSino opcionSinoByEsHabilitado, Organizacion organizacion, OpcionSino opcionSinoByEsPersonaContactoRequired, CodigoPostal codigoPostal, String rifOrganizacion, String nitOrganizacion, String razonOrganizacion, String telefonoFijoOrganizacion, String telefonoSecundarioOrganizacion, String EMailOrganizacion, String direccionOrganizacion, String cabecera, String url1, String url1FileName, Double url1FileSize, String formatoCabecera, String formatoPiePagina, String formatoFirma, Long nextNroPedido, String numeroImpFiscal, String usuarioCreacion, LocalDateTime fechaCreacion, String usuarioModificacion, LocalDateTime fechaModificacion, Integer maxOrganizacionesPorGrupo, Integer maxSedesPorOrganizacion, String tituloResponsable, String nombreResponsable, Set<PropiedadesSistema> propiedadesSistemas, Set<UsuarioOrganizacion> usuarioOrganizacionsForIdOrganizacion, Set<PersonaOrganizacion> personaOrganizacions, Set<UsuarioOrganizacion> usuarioOrganizacionsForIdSede, Set<Organizacion> organizacions, Set<UsuarioOrganizacion> usuarioOrganizacionsForIdSedeDefault) {
       this.tipoOrganizacion = tipoOrganizacion;
       this.opcionSinoByEsHabilitado = opcionSinoByEsHabilitado;
       this.organizacion = organizacion;
       this.opcionSinoByEsPersonaContactoRequired = opcionSinoByEsPersonaContactoRequired;
       this.codigoPostal = codigoPostal;
       this.rifOrganizacion = rifOrganizacion;
       this.nitOrganizacion = nitOrganizacion;
       this.razonOrganizacion = razonOrganizacion;
       this.telefonoFijoOrganizacion = telefonoFijoOrganizacion;
       this.telefonoSecundarioOrganizacion = telefonoSecundarioOrganizacion;
       this.EMailOrganizacion = EMailOrganizacion;
       this.direccionOrganizacion = direccionOrganizacion;
       this.cabecera = cabecera;
       this.url1 = url1;
       this.url1FileName = url1FileName;
       this.url1FileSize = url1FileSize;
       this.formatoCabecera = formatoCabecera;
       this.formatoPiePagina = formatoPiePagina;
       this.formatoFirma = formatoFirma;
       this.nextNroPedido = nextNroPedido;
       this.numeroImpFiscal = numeroImpFiscal;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.maxOrganizacionesPorGrupo = maxOrganizacionesPorGrupo;
       this.maxSedesPorOrganizacion = maxSedesPorOrganizacion;
       this.tituloResponsable = tituloResponsable;
       this.nombreResponsable = nombreResponsable;
       this.propiedadesSistemas = propiedadesSistemas;
       this.usuarioOrganizacionsForIdOrganizacion = usuarioOrganizacionsForIdOrganizacion;
       this.personaOrganizacions = personaOrganizacions;
       this.usuarioOrganizacionsForIdSede = usuarioOrganizacionsForIdSede;
       this.organizacions = organizacions;
       this.usuarioOrganizacionsForIdSedeDefault = usuarioOrganizacionsForIdSedeDefault;
    }
   
  @GenericGenerator(name = "organizacion_seq_gen", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @Parameter(name = "sequence_name", value = "organizacion_id_seq"),
                    @Parameter(name = "initial_value", value = "1"),
                    @Parameter(name = "increment_size", value = "1")
            })
  @GeneratedValue(generator = "organizacion_seq_gen")
  @Id
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_organizacion")
    public TipoOrganizacion getTipoOrganizacion() {
        return this.tipoOrganizacion;
    }
    
    public void setTipoOrganizacion(TipoOrganizacion tipoOrganizacion) {
        this.tipoOrganizacion = tipoOrganizacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="es_habilitado", nullable=false)
    public OpcionSino getOpcionSinoByEsHabilitado() {
        return this.opcionSinoByEsHabilitado;
    }
    
    public void setOpcionSinoByEsHabilitado(OpcionSino opcionSinoByEsHabilitado) {
        this.opcionSinoByEsHabilitado = opcionSinoByEsHabilitado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_organizacion_padre")
    public Organizacion getOrganizacion() {
        return this.organizacion;
    }
    
    public void setOrganizacion(Organizacion organizacion) {
        this.organizacion = organizacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="es_persona_contacto_required")
    public OpcionSino getOpcionSinoByEsPersonaContactoRequired() {
        return this.opcionSinoByEsPersonaContactoRequired;
    }
    
    public void setOpcionSinoByEsPersonaContactoRequired(OpcionSino opcionSinoByEsPersonaContactoRequired) {
        this.opcionSinoByEsPersonaContactoRequired = opcionSinoByEsPersonaContactoRequired;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_codigo_postal")
    public CodigoPostal getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(CodigoPostal codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    
    @Column(name="rif_organizacion", nullable=false, length=64)
    public String getRifOrganizacion() {
        return this.rifOrganizacion;
    }
    
    public void setRifOrganizacion(String rifOrganizacion) {
        this.rifOrganizacion = rifOrganizacion;
    }
    
    @Column(name="nit_organizacion", length=64)
    public String getNitOrganizacion() {
        return this.nitOrganizacion;
    }
    
    public void setNitOrganizacion(String nitOrganizacion) {
        this.nitOrganizacion = nitOrganizacion;
    }
    
    @Column(name="razon_organizacion", nullable=false)
    public String getRazonOrganizacion() {
        return this.razonOrganizacion;
    }
    
    public void setRazonOrganizacion(String razonOrganizacion) {
        this.razonOrganizacion = razonOrganizacion;
    }
    
    @Column(name="telefono_fijo_organizacion", length=32)
    public String getTelefonoFijoOrganizacion() {
        return this.telefonoFijoOrganizacion;
    }
    
    public void setTelefonoFijoOrganizacion(String telefonoFijoOrganizacion) {
        this.telefonoFijoOrganizacion = telefonoFijoOrganizacion;
    }
    
    @Column(name="telefono_secundario_organizacion", length=32)
    public String getTelefonoSecundarioOrganizacion() {
        return this.telefonoSecundarioOrganizacion;
    }
    
    public void setTelefonoSecundarioOrganizacion(String telefonoSecundarioOrganizacion) {
        this.telefonoSecundarioOrganizacion = telefonoSecundarioOrganizacion;
    }
    
    @Column(name="e_mail_organizacion", length=64)
    public String getEMailOrganizacion() {
        return this.EMailOrganizacion;
    }
    
    public void setEMailOrganizacion(String EMailOrganizacion) {
        this.EMailOrganizacion = EMailOrganizacion;
    }
    
    @Column(name="direccion_organizacion")
    public String getDireccionOrganizacion() {
        return this.direccionOrganizacion;
    }
    
    public void setDireccionOrganizacion(String direccionOrganizacion) {
        this.direccionOrganizacion = direccionOrganizacion;
    }
    
    @Column(name="cabecera")
    public String getCabecera() {
        return this.cabecera;
    }
    
    public void setCabecera(String cabecera) {
        this.cabecera = cabecera;
    }
    
    @Column(name="url1")
    public String getUrl1() {
        return this.url1;
    }
    
    public void setUrl1(String url1) {
        this.url1 = url1;
    }
    
    @Column(name="url1_file_name")
    public String getUrl1FileName() {
        return this.url1FileName;
    }
    
    public void setUrl1FileName(String url1FileName) {
        this.url1FileName = url1FileName;
    }
    
    @Column(name="url1_file_size", precision=17, scale=17)
    public Double getUrl1FileSize() {
        return this.url1FileSize;
    }
    
    public void setUrl1FileSize(Double url1FileSize) {
        this.url1FileSize = url1FileSize;
    }
    
    @Column(name="formato_cabecera")
    public String getFormatoCabecera() {
        return this.formatoCabecera;
    }
    
    public void setFormatoCabecera(String formatoCabecera) {
        this.formatoCabecera = formatoCabecera;
    }
    
    @Column(name="formato_pie_pagina")
    public String getFormatoPiePagina() {
        return this.formatoPiePagina;
    }
    
    public void setFormatoPiePagina(String formatoPiePagina) {
        this.formatoPiePagina = formatoPiePagina;
    }
    
    @Column(name="formato_firma")
    public String getFormatoFirma() {
        return this.formatoFirma;
    }
    
    public void setFormatoFirma(String formatoFirma) {
        this.formatoFirma = formatoFirma;
    }
    
    @Column(name="next_nro_pedido")
    public Long getNextNroPedido() {
        return this.nextNroPedido;
    }
    
    public void setNextNroPedido(Long nextNroPedido) {
        this.nextNroPedido = nextNroPedido;
    }
    
    @Column(name="numero_imp_fiscal", length=128)
    public String getNumeroImpFiscal() {
        return this.numeroImpFiscal;
    }
    
    public void setNumeroImpFiscal(String numeroImpFiscal) {
        this.numeroImpFiscal = numeroImpFiscal;
    }
    
    @Column(name="usuario_creacion", length=64)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    
    @Column(name="fecha_creacion", length=29)
    public LocalDateTime getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(LocalDateTime fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="usuario_modificacion", length=64)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    
    @Column(name="fecha_modificacion", length=29)
    public LocalDateTime getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(LocalDateTime fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    
    @Column(name="max_organizaciones_por_grupo")
    public Integer getMaxOrganizacionesPorGrupo() {
        return this.maxOrganizacionesPorGrupo;
    }
    
    public void setMaxOrganizacionesPorGrupo(Integer maxOrganizacionesPorGrupo) {
        this.maxOrganizacionesPorGrupo = maxOrganizacionesPorGrupo;
    }
    
    @Column(name="max_sedes_por_organizacion")
    public Integer getMaxSedesPorOrganizacion() {
        return this.maxSedesPorOrganizacion;
    }
    
    public void setMaxSedesPorOrganizacion(Integer maxSedesPorOrganizacion) {
        this.maxSedesPorOrganizacion = maxSedesPorOrganizacion;
    }
    
    @Column(name="titulo_responsable", length=64)
    public String getTituloResponsable() {
        return this.tituloResponsable;
    }
    
    public void setTituloResponsable(String tituloResponsable) {
        this.tituloResponsable = tituloResponsable;
    }
    
    @Column(name="nombre_responsable", length=64)
    public String getNombreResponsable() {
        return this.nombreResponsable;
    }
    
    public void setNombreResponsable(String nombreResponsable) {
        this.nombreResponsable = nombreResponsable;
    }
	@JsonIgnore
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organizacion")
    public Set<PropiedadesSistema> getPropiedadesSistemas() {
        return this.propiedadesSistemas;
    }
    
    public void setPropiedadesSistemas(Set<PropiedadesSistema> propiedadesSistemas) {
        this.propiedadesSistemas = propiedadesSistemas;
    }
	@JsonIgnore
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organizacionByIdOrganizacion")
    public Set<UsuarioOrganizacion> getUsuarioOrganizacionsForIdOrganizacion() {
        return this.usuarioOrganizacionsForIdOrganizacion;
    }
    
    public void setUsuarioOrganizacionsForIdOrganizacion(Set<UsuarioOrganizacion> usuarioOrganizacionsForIdOrganizacion) {
        this.usuarioOrganizacionsForIdOrganizacion = usuarioOrganizacionsForIdOrganizacion;
    }
	@JsonIgnore
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organizacion")
    public Set<PersonaOrganizacion> getPersonaOrganizacions() {
        return this.personaOrganizacions;
    }
    
    public void setPersonaOrganizacions(Set<PersonaOrganizacion> personaOrganizacions) {
        this.personaOrganizacions = personaOrganizacions;
    }
	@JsonIgnore
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organizacionByIdSede")
    public Set<UsuarioOrganizacion> getUsuarioOrganizacionsForIdSede() {
        return this.usuarioOrganizacionsForIdSede;
    }
    
    public void setUsuarioOrganizacionsForIdSede(Set<UsuarioOrganizacion> usuarioOrganizacionsForIdSede) {
        this.usuarioOrganizacionsForIdSede = usuarioOrganizacionsForIdSede;
    }
	@JsonIgnore
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organizacion")
    public Set<Organizacion> getOrganizacions() {
        return this.organizacions;
    }
    
    public void setOrganizacions(Set<Organizacion> organizacions) {
        this.organizacions = organizacions;
    }
	@JsonIgnore
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organizacionByIdSedeDefault")
    public Set<UsuarioOrganizacion> getUsuarioOrganizacionsForIdSedeDefault() {
        return this.usuarioOrganizacionsForIdSedeDefault;
    }
    
    public void setUsuarioOrganizacionsForIdSedeDefault(Set<UsuarioOrganizacion> usuarioOrganizacionsForIdSedeDefault) {
        this.usuarioOrganizacionsForIdSedeDefault = usuarioOrganizacionsForIdSedeDefault;
    }

    /**
     * toString
     * @return String
     */
     @Override
     public String toString() {
	  StringBuilder buffer = new StringBuilder();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("tipoOrganizacion").append("='").append(getTipoOrganizacion()).append("' ");			
      buffer.append("opcionSinoByEsHabilitado").append("='").append(getOpcionSinoByEsHabilitado()).append("' ");			
      buffer.append("organizacion").append("='").append(getOrganizacion()).append("' ");			
      buffer.append("opcionSinoByEsPersonaContactoRequired").append("='").append(getOpcionSinoByEsPersonaContactoRequired()).append("' ");			
      buffer.append("codigoPostal").append("='").append(getCodigoPostal()).append("' ");			
      buffer.append("rifOrganizacion").append("='").append(getRifOrganizacion()).append("' ");			
      buffer.append("nitOrganizacion").append("='").append(getNitOrganizacion()).append("' ");			
      buffer.append("razonOrganizacion").append("='").append(getRazonOrganizacion()).append("' ");			
      buffer.append("telefonoFijoOrganizacion").append("='").append(getTelefonoFijoOrganizacion()).append("' ");			
      buffer.append("telefonoSecundarioOrganizacion").append("='").append(getTelefonoSecundarioOrganizacion()).append("' ");			
      buffer.append("EMailOrganizacion").append("='").append(getEMailOrganizacion()).append("' ");			
      buffer.append("direccionOrganizacion").append("='").append(getDireccionOrganizacion()).append("' ");			
      buffer.append("cabecera").append("='").append(getCabecera()).append("' ");			
      buffer.append("url1").append("='").append(getUrl1()).append("' ");			
      buffer.append("url1FileName").append("='").append(getUrl1FileName()).append("' ");			
      buffer.append("url1FileSize").append("='").append(getUrl1FileSize()).append("' ");			
      buffer.append("formatoCabecera").append("='").append(getFormatoCabecera()).append("' ");			
      buffer.append("formatoPiePagina").append("='").append(getFormatoPiePagina()).append("' ");			
      buffer.append("formatoFirma").append("='").append(getFormatoFirma()).append("' ");			
      buffer.append("nextNroPedido").append("='").append(getNextNroPedido()).append("' ");			
      buffer.append("numeroImpFiscal").append("='").append(getNumeroImpFiscal()).append("' ");			
      buffer.append("usuarioCreacion").append("='").append(getUsuarioCreacion()).append("' ");			
      buffer.append("fechaCreacion").append("='").append(getFechaCreacion()).append("' ");			
      buffer.append("usuarioModificacion").append("='").append(getUsuarioModificacion()).append("' ");			
      buffer.append("fechaModificacion").append("='").append(getFechaModificacion()).append("' ");			
      buffer.append("maxOrganizacionesPorGrupo").append("='").append(getMaxOrganizacionesPorGrupo()).append("' ");			
      buffer.append("maxSedesPorOrganizacion").append("='").append(getMaxSedesPorOrganizacion()).append("' ");			
      buffer.append("tituloResponsable").append("='").append(getTituloResponsable()).append("' ");			
      buffer.append("nombreResponsable").append("='").append(getNombreResponsable()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

	@Override
	public boolean equals(Object other) {
         if (this == other) 
         	return true;
         	
		 if (other == null) 
		 	return false;
		 	
		 if (!(other instanceof Organizacion)) 
		 	return false;
		 	
		 Organizacion castOther = ( Organizacion ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && (this.getVersion()==castOther.getVersion());
   }
   
   @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + (int) this.getVersion();
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   

  // The following is extra code specified in src/main/config/templates
// Adding extra-code
	private boolean comesFromExternalDataSource = false;
	private boolean selected;
	
	@javax.persistence.Transient
    public boolean isExternalDataSource() {
		return this.comesFromExternalDataSource;
    }

    public void setExternalDataSource(boolean value) {
        this.comesFromExternalDataSource = value;
    }

	@javax.persistence.Transient
	public boolean getSelected() {
		return selected;
	}

    public void setSelected(boolean selected) {
		this.selected = selected;
    }
    
    public void cleanPOJO() {
		if(this.tipoOrganizacion != null &&
			(tipoOrganizacion.getId() == null || this.tipoOrganizacion.getId().longValue() == 0)) {
			tipoOrganizacion = null;
		}
		if(this.opcionSinoByEsHabilitado != null &&
			(opcionSinoByEsHabilitado.getId() == null || this.opcionSinoByEsHabilitado.getId().longValue() == 0)) {
			opcionSinoByEsHabilitado = null;
		}
		if(this.organizacion != null &&
			(organizacion.getId() == null || this.organizacion.getId().longValue() == 0)) {
			organizacion = null;
		}
		if(this.opcionSinoByEsPersonaContactoRequired != null &&
			(opcionSinoByEsPersonaContactoRequired.getId() == null || this.opcionSinoByEsPersonaContactoRequired.getId().longValue() == 0)) {
			opcionSinoByEsPersonaContactoRequired = null;
		}
		if(this.codigoPostal != null &&
			(codigoPostal.getId() == null || this.codigoPostal.getId().longValue() == 0)) {
			codigoPostal = null;
		}
    }
    
    public void fillPOJO() {
		if(this.tipoOrganizacion == null) {
			tipoOrganizacion = new TipoOrganizacion();
		}
		if(this.opcionSinoByEsHabilitado == null) {
			opcionSinoByEsHabilitado = new OpcionSino();
		}
		if(this.organizacion == null) {
			organizacion = new Organizacion();
		}
		if(this.opcionSinoByEsPersonaContactoRequired == null) {
			opcionSinoByEsPersonaContactoRequired = new OpcionSino();
		}
		if(this.codigoPostal == null) {
			codigoPostal = new CodigoPostal();
		}
    }
    
    public Organizacion createPOJO() {
		fillPOJO();
		
		return this;
	}
	
//	@PrePersist
//	public void onPrePersist() {
//		this.fechaCreacion = new Date();
//		this.usuarioCreacion = getSecurityContextPrincipal();
//	}
//
//	@PreUpdate
//	public void onPreUpdate() {
//		this.fechaModificacion = new Date();
//		this.usuarioModificacion = getSecurityContextPrincipal();
//	}
//
//	@javax.persistence.Transient
//	private String getSecurityContextPrincipal() {
//		String principal;
//		String UNKNOWN_USER = "unknownUser";
//
//		if (SecurityContextHolder.getContext().getAuthentication() == null) {
//			principal = UNKNOWN_USER;
//		} else {
//			try {
//				principal = ((User) SecurityContextHolder.getContext().getAuthentication().getPrincipal())
//						.getUsername();
//			} catch (ClassCastException e) {
//				principal = UNKNOWN_USER;
//			}
//		}
//
//		return principal;
//	}
	
  // end of extra code specified in the hbm.xml files

}

